spring:
  application:
    name: flowguard-server
  
  datasource:
    # URL configurada com p6spy
    url: jdbc:p6spy:postgresql://localhost:5432/flowguard
    username: flowguard_user
    password: flowguard_password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/flowguard # Flyway bypasses p6spy
    user: flowguard_user
    password: flowguard_password

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:8f830a3b2b800ea011b025f82c2a0d1e57c5a08db1b92040b10626a7e0a8163f}
  expiration-ms: 86400000 # 24 hours
